version: '{build}'

branches:
  only:
    - master

platform:
  - x64

services:
  - mssql2017

shallow_clone: true

install:
  - ps: Install-Product node 10 x64
  - node --version
  - npm --version
  - npm install

build: off

before_test:
  - ps: . .\scripts\appveyor-setup.ps1

test_script:
  - npm run test:mssql
