version: '2'

services:
  sequelizr:
    build: .
    links:
     - mysql-80
    volumes:
      - .:/sequelizr
    environment:
      SEQ_DB: sequelizr_test
      SEQ_USER: sequelizr_test
      SEQ_PW: sequelizr_test

  # MySQL
  mysql-80:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: lollerskates
      MYSQL_DATABASE: sequelizr_test
      MYSQL_USER: sequelizr_test
      MYSQL_PASSWORD: sequelizr_test
    volumes:
    - $MYSQLDB_ENTRYPOINT:/docker-entrypoint-initdb.d
    ports:
      - "8980:3306"
    container_name: mysql-80
